# Hecate-Nautilus: Manifesto de Orquestração v2.0 (Corrigido)
services:
  unbound:
    build:
      context: ./unbound
      dockerfile: Dockerfile
    container_name: hecate-unbound
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./unbound/config/unbound.conf:/etc/unbound/unbound.conf:ro
      - ./unbound/config/root.key:/etc/unbound/root.key:ro
    # !! IMPORTANTE: Ajuste o cpuset para os núcleos do seu CPU Xeon !!
    cpuset: "2-13"
    mem_limit: 10g
    cap_add:
      - NET_ADMIN

  adguard:
    image: adguard/adguardhome:latest
    container_name: hecate-adguard
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/config:/opt/adguardhome/conf
    # !! IMPORTANTE: Ajuste o cpuset !!
    cpuset: "0-1"
    mem_limit: 2g

  redis:
    image: redis:7-alpine
    container_name: hecate-redis
    restart: unless-stopped
    # Exposto apenas localmente para os outros contêineres
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    # !! IMPORTANTE: Ajuste o cpuset !!
    cpuset: "14"
    mem_limit: 2g
