services:
  unbound:
    build:
      context: ./unbound
    container_name: hecate-unbound
    restart: unless-stopped
    network_mode: "host"           # em Windows, override muda isso
    volumes:
      - ./unbound/config:/config:ro
    ulimits:
      nofile: 262144
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /var/run/unbound:size=8m,mode=755
