services:
  unbound:
    build:
      context: ./unbound
    container_name: hecate-unbound
    restart: unless-stopped
    # Em Linux, host é ok. No Windows, use o override com ports.
    network_mode: "host"
    volumes:
      - ./unbound/config:/config:ro
      - unbound_etc:/etc/unbound
    read_only: false
    tmpfs:
      - /var/run/unbound:size=8m,mode=755

volumes:
  unbound_etc:
