services:
  unbound:
    build:
      context: .
      dockerfile: unbound/Dockerfile
    container_name: hecate-nautilus
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
