services:
  unbound:
    build:
      context: ./unbound
    container_name: hecate-unbound
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./unbound/config/unbound.conf:/etc/unbound/unbound.conf:ro
      - ./unbound/config/root.hints:/etc/unbound/root.hints:ro
      - unbound_state:/var/lib/unbound

  adguard:
    image: adguard/adguardhome:latest
    container_name: hecate-adguard
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/config:/opt/adguardhome/conf

  redis:
    image: redis:7-alpine
    container_name: hecate-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis/data:/data
    command: ["redis-server","--appendonly","no"]

volumes:
  unbound_state:
